[429] - SwiftUI Controls Refactroing
admiral-team/admiralui-ios pull request #431
Opened 2022-08-30 05:37 UTC by KirBorisov96

# Задача

## Что было сделано
- SeveralPinButton
- TagControl
- PrimaryLinkControl

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-08-30 05:50 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1362
Version: 1661838235
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/2
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1362

2022-08-31 06:40 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1385
Version: 1661927571
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/2
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1385

2022-08-31 11:37 UTC, Evgeniy-93 approved these changes

2022-08-31 12:28 UTC, Almazovivan commented on Source/AdmiralSwiftUI/Classes/Components/Controls/Pin/PinButtonStyle.swift
> -        let scheme = scheme ?? schemeProvider.scheme
Почему мы убрали возможность брать схему из схемпровайдера?

2022-08-31 12:29 UTC, Almazovivan commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SeveralPin/SeveralPinButtonStyle.swift
> -        let scheme = scheme ?? schemeProvider.scheme
Тут тоже?

2022-08-31 15:08 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/Pin/PinButtonStyle.swift
> -        let scheme = scheme ?? schemeProvider.scheme
посмотри код внимательнее. Там есть view и есть ButtonStyle

2022-08-31 15:08 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SeveralPin/SeveralPinButtonStyle.swift
> -        let scheme = scheme ?? schemeProvider.scheme
посмотри код внимательнее.

2022-08-31 15:10 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/Pin/PinButtonStyle.swift
> -        let scheme = scheme ?? schemeProvider.scheme
одно дело если мы будем передавать кастомные провайдер, тогда конечно нужно его тащить. Но у нас логика другая, если схема отсутсвует то используется схема с дефолтными настройками из провайдера.

2022-09-02 08:16 UTC, Andyatkov requested changes

2022-09-02 08:16 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/Pin/PinButtonScheme.swift
> +    public init(theme: AppTheme = .default) {
Давай вызовем другой конструктор и туда передавать значения. Давай избегать дублирования кода

2022-09-02 08:16 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SeveralPin/SeveralPinButtonScheme.swift
> +    public init(theme: AppTheme = .default) {
Давай вызовем другой конструктор и туда передавать значения. Давай избегать дублирования кода

2022-09-02 08:16 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/LinkControl/PrimaryLinkControl/PrimaryLinkControl.swift
> +    /// The image of PrimaryLinkControl
Зачем нужно "of PrimaryLinkControl" ?

2022-09-02 08:16 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/LinkControl/PrimaryLinkControl/PrimaryLinkControlScheme.swift
>      public init(theme: AppTheme) {
Давай вызовем другой конструктор и туда передавать значения. Давай избегать дублирования кода

2022-09-02 09:16 UTC, ton252 approved these changes

2022-09-02 09:16 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SeveralPin/SeveralPinButtonStyle.swift
>      public func makeBody(configuration: Self.Configuration) -> some View {
++

2022-09-05 12:48 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1419
Version: 1662381124
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/2
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1419

2022-09-06 06:25 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1426
Version: 1662445115
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/2
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1426

2022-09-06 14:10 UTC, Almazovivan approved these changes

2022-09-06 15:51 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1448
Version: 1662479068
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/2
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1448

2022-09-06 16:20 UTC, Almazovivan submitted a review, later dismissed

2022-09-06 19:22 UTC, Andyatkov requested changes

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/Pin/PinButtonScheme.swift
> +    /// The selected backgroundColor of PinButton
Зачем of PinButton?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/Pin/PinButtonScheme.swift
> +    /// The background color of PinButton
Зачем of PinButton?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/Pin/PinButtonScheme.swift
> +    /// The shadow color of PinButton
Зачем of PinButton?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/Pin/PinButtonStyle.swift
> +    /// The selection flag of PinButtonStyle
Зачем of PinButtonStyle?
Про isSelected можно посмотреть в доку apple как лучше описать

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SeveralPin/SeveralPinButtonScheme.swift
> +    /// The border color of SeveralPinButton
Зачем of SeveralPinButton?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SeveralPin/SeveralPinButtonScheme.swift
> +    /// The background color of SeveralPinButton
Зачем of SeveralPinButton?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SeveralPin/SeveralPinButtonScheme.swift
> +    /// The text color of SeveralPinButton
Зачем of SeveralPinButton?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SeveralPin/SeveralPinButtonScheme.swift
> +    /// The shadow color of SeveralPinButton
Зачем of SeveralPinButton?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/LinkControl/PrimaryLinkControl/PrimaryLinkControlScheme.swift
> +    /// The font color of PrimaryLinkControl
Зачем of PrimaryLinkControl?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/LinkControl/PrimaryLinkControl/PrimaryLinkControlScheme.swift
> +    /// The text color of PrimaryLinkControl
Зачем of PrimaryLinkControl?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/TagControl.swift
> +    /// The attention style of TagControl
Зачем of TagControl?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/TagControl.swift
> +    /// The error style of TagControl
Зачем of TagControl?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/TagControl.swift
> +    /// The additional style of TagControl
Зачем of TagControl?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/TagControl.swift
> +    /// The success style of TagControl
Зачем of TagControl?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/TagControl.swift
> +    /// The default style of TagControl
Зачем of TagControl?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/TagControl.swift
> +    /// The none style of TagControl
Зачем of TagControl?

2022-09-06 19:22 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/TagControl/TagControlScheme.swift
> +    /// The font of TagControl
Зачем of TagControl?

2022-09-07 07:48 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1471
Version: 1662536469
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/2
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1471

2022-09-07 09:29 UTC, Andyatkov approved these changes

2022-09-07 10:01 UTC, merged