[429] - SwiftUI Controls Refactoring
admiral-team/admiralui-ios pull request #432
Opened 2022-08-30 05:52 UTC by KirBorisov96

# Задача
ToolBar рефакторинг

## Что было сделано

ToolBar

## Что необходимо протестировать

SwiftUI -> ToolBar

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-08-30 06:01 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1363
Version: 1661838873
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1363

2022-08-30 07:05 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1369
Version: 1661842685
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1369

2022-08-30 11:53 UTC, Evgeniy-93 approved these changes

2022-09-02 09:18 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemScheme.swift
> +    public init(theme: AppTheme = .default) {
где инициализатор через параметры?

2022-09-02 09:19 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarScheme.swift
>      public init(theme: AppTheme) {
.default

2022-09-05 12:58 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1420
Version: 1662382186
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1420

2022-09-06 06:17 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1425
Version: 1662444586
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1425

2022-09-06 16:20 UTC, Almazovivan approved these changes

2022-09-06 19:18 UTC, Andyatkov requested changes

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItem.swift
> +    /// The title of ToolBar
Зачем of ToolBar?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItem.swift
> +    /// The image of ToolBar
Зачем of ToolBar?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItem.swift
> +    /// The badge style of ToolBar
Зачем of ToolBar? 
Здесь хорошо дописать на что влияет badge style и какие бывают

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItem.swift
> +    /// The type of ToolBar
Зачем of ToolBar? 
Здесь круто описать бы зачем нужен type и на что влияет

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemScheme.swift
> +    /// The title color of ToolBarItem
Зачем of ToolBarItem?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemScheme.swift
> +    /// The image color of ToolBarItem
Зачем of ToolBarItem?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemScheme.swift
> +    /// The horizontal title label font of ToolBarItem
Зачем of ToolBarItem?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemScheme.swift
> +    /// The vertical title label font of ToolBarItem
Зачем of ToolBarItem?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemScheme.swift
> +    /// The border color of ToolBarItem
Зачем of ToolBarItem?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +//  Created by Борисов Кирилл Анатольевич on 22.08.2022.
Норм что тут твое имя?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +                            .frame(width: 32.0, height: 32.0)
magic const
И кстати 8 * 4 = 32 и у нас в Гриде для этого есть заготовка

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +                            .frame(width: 32.0, height: 32.0)
magic const
И кстати 8 * 4 = 32 и у нас в Гриде для этого есть заготовка

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +                    .frame(width: 32.0, height: 32.0)
magic const
И кстати 8 * 4 = 32 и у нас в Гриде для этого есть заготовка

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +                image
image
                     .renderingMode(.template)
                     .foregroundColor(imageColor)
                     .frame(width: 32.0, height: 32.0)
                     
очень просится вынести, ну прям очень

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarViewRouter.swift
> +final class ToolBarViewRouter: ObservableObject {
В библиотеке компонентов не должно быть упоминание о любой архитектуры, такие как ViewModel, Interactor, Router и тд,
зачем нужно было выносить это отдельный класс мне не очень понятно

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The enabled flag of ToolBarItem
Зачем  of ToolBarItem

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The itemType of ToolBarItem
Зачем of ToolBarItem

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The itemType of ToolBarItem
Здесь еще надо описать на что влияет и какие типы бывают

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The selection flag of ToolBarItem
Зачем of ToolBarItem
 Про selection можно красивее написать, например посмотреть в apple.com:
"A Boolean value that indicates whether the view is selected." 
Мне кажется за*бись, что думаешь?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The scheme of ToolBarItem
Зачем of ToolBarItem?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The badge style of ToolBarItem
Зачем of ToolBarItem?
На что влияет badge style и какие бывают - нужно дописать

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The title of ToolBarItem
Зачем of ToolBarItem?

2022-09-06 19:18 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The image of ToolBarItem
Зачем of ToolBarItem?

2022-09-07 09:23 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +//  Created by Борисов Кирилл Анатольевич on 22.08.2022.
нет, не норм

2022-09-07 09:35 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +                image
вынес

2022-09-07 09:37 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The badge style of ToolBarItem
+

2022-09-07 09:37 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemStyle.swift
> +    /// The selection flag of ToolBarItem
согласен, там много где надо поправить

2022-09-07 09:52 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarViewRouter.swift
> +final class ToolBarViewRouter: ObservableObject {
затем что хранить вне сущности в одном файле не круто, тем более мы упомянули что класс не публичный

2022-09-07 10:09 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1475
Version: 1662544954
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1475

2022-09-07 10:19 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1476
Version: 1662545496
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1476

2022-09-07 10:28 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1477
Version: 1662546041
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1477

2022-09-08 10:48 UTC, KirBorisov96 commented
CI отвалился, собрал сборочку сам
[13:46:51]: Finishing release...
[13:46:52]: Upload finished
[13:46:53]: Waiting for release to be ready...
[13:47:35]: Release '1478' committed: https://appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/distribute/releases/1478
[13:47:37]: Release '1478' (0.0.0) was successfully updated
[13:47:39]: Release '1478' (0.0.0) was successfully distributed'
[13:47:39]: Release '1478' (0.0.0) was successfully distributed to group "Internal Testers"
[13:47:41]: Release '1478' (0.0.0) was successfully distributed'
[13:47:41]: Release '1478' (0.0.0) was successfully distributed to group "Collaborators"
[13:47:41]: Release '1478' is available for download at: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev
[13:47:41]: Starting dSYM upload...
[13:47:42]: Uploading dSYM...
[13:47:48]: dSYM uploaded

2022-09-09 11:35 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1482
Version: 1662722900
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1482

2022-09-09 15:29 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1506
Version: 1662736912
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1506

2022-09-09 15:38 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1507
Version: 1662737455
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1507

2022-09-12 06:17 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBar.swift
> +                    radius: 14.0,
Надо вынести в константы

2022-09-12 06:17 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItem.swift
> +    /// Sets default image color of ToolBarItem
of ToolBarItem

2022-09-12 06:17 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItem.swift
> +    /// Sets default image color of ToolBarItem
и ниже

2022-09-12 06:17 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +    // MARK: - Internal Properties
Два пробела перед // MARK: - Internal Properties

2022-09-12 09:06 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBarItem/ToolBarItemSelectable.swift
> +    // MARK: - Internal Properties
да там вроде норм все с выравниванием

2022-09-12 09:20 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1530
Version: 1662973981
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1530

2022-09-12 10:08 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1534
Version: 1662976835
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1534

2022-09-12 13:14 UTC, Evgeniy-93 submitted a review, later dismissed

2022-09-12 13:23 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBar.swift
> +    /// The value that sets specific font and color of ToolBarItem
of ToolBarItem

2022-09-12 13:23 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBar.swift
> +    /// The value that sets specific font and color of ToolBarItem
of ToolBarItem

2022-09-12 13:52 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1544
Version: 1662990307
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1544

2022-09-12 14:00 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1545
Version: 1662990818
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1545

2022-09-15 07:59 UTC, Andyatkov requested changes

2022-09-15 07:59 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBar.swift
> +    /// The value that sets specific font and color
Ухххх, жестко
ToolBarType служит расположение текста когда в тулбаре один элемент, либо он становится вертикально(под картинкой текст), либо горизонтально(справа от картинки будет текст)

2022-09-15 07:59 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBar.swift
> +        static let height: CGFloat = 48.0
Почему мы не юзаем Грид??

Объясняю зачем нужен грид
Если поменяется сетка(у нас сейчас отступы равны 16 = два модуля) например на 10(модуль станет равен 10), то нам придется выискивать места, где люди положили болт на сетку, а это очень не приятное занятие, поэтому очень прошу не забывать про Грид и если еще где то видел такое, то там тоже нужно поправить.

2022-09-15 09:27 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1574
Version: 1663233597
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1574

2022-09-15 09:37 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1575
Version: 1663234185
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1575

2022-09-15 09:40 UTC, Andyatkov approved these changes

2022-09-15 09:40 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/ToolBar/ToolBar.swift
> +        static let width: CGFloat = UIScreen.main.bounds.width - 72.0
72.0 = 8 * 9 = module * 9

2022-09-15 09:42 UTC, Andyatkov approved these changes

2022-09-15 09:52 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1576
Version: 1663235069
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1576

2022-09-15 09:52 UTC, merged