[429] - SwiftUI Refactoring
admiral-team/admiralui-ios pull request #437
Opened 2022-08-30 07:05 UTC by KirBorisov96

# Задача
SwiftUI:
- LogoTab
- OutlineSliderTab

## Что было сделано
SwiftUI:
- LogoTab
- OutlineSliderTab

## Что необходимо протестировать
SwiftUI:
- LogoTab
- OutlineSliderTab
## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-08-31 07:47 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1390
Version: 1661931611
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/8
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1390

2022-08-31 11:55 UTC, Evgeniy-93 approved these changes

2022-08-31 11:58 UTC, Almazovivan submitted a review, later dismissed

2022-09-02 09:49 UTC, ton252 submitted a review, later dismissed

2022-09-02 09:49 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/LogoTab/LogoTabScheme.swift
>      public init(theme: AppTheme) {
convenience init

2022-09-02 09:49 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/LogoTab/LogoTabScheme.swift
> +    public init(
parameterbox

2022-09-02 09:49 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/OutlineSliderTab/OutlineSliderTabScheme.swift
> +    public init(theme: AppTheme = .default) {
convenience init

2022-09-02 09:49 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/OutlineSliderTab/OutlineSliderTabScheme.swift
> +    public init(
parameterbox

2022-09-06 12:41 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1437
Version: 1662467629
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/8
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1437

2022-09-06 16:09 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1450
Version: 1662480121
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/8
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1450

2022-09-06 16:22 UTC, Almazovivan approved these changes

2022-09-06 17:21 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1458
Version: 1662484463
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/8
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1458

2022-09-06 19:03 UTC, Andyatkov requested changes

2022-09-06 19:03 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/OutlineSliderTab/OutlineSliderTabItem.swift
> +     public var badgeStyle: BadgeStyle?
Лучше let

2022-09-07 07:39 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1470
Version: 1662535933
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/8
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1470

2022-09-08 11:44 UTC, KirBorisov96 commented
Собрал сборку сам 
[14:42:55]: Waiting for release to be ready...
[14:43:25]: Release '1479' committed: https://appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/distribute/releases/1479
[14:43:27]: Release '1479' (0.0.0) was successfully updated
[14:43:29]: Release '1479' (0.0.0) was successfully distributed'
[14:43:29]: Release '1479' (0.0.0) was successfully distributed to group "Internal Testers"
[14:43:31]: Release '1479' (0.0.0) was successfully distributed'
[14:43:31]: Release '1479' (0.0.0) was successfully distributed to group "Collaborators"
[14:43:31]: Release '1479' is available for download at: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev
[14:43:31]: Starting dSYM upload...
[14:43:31]: Uploading dSYM...
[14:43:52]: dSYM uploaded

2022-09-09 11:44 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1483
Version: 1662723436
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/429-swiftui-conrols/8
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1483

2022-09-09 12:58 UTC, Evgeniy-93 approved these changes

2022-09-12 06:18 UTC, Andyatkov approved these changes

2022-09-12 08:09 UTC, merged