[392] - SwiftUI Views Refactoring ChatBubbleView
admiral-team/admiralui-ios pull request #442
Opened 2022-08-30 08:43 UTC by KirBorisov96

# Задача

SwiftUI:
- ChatBubbleView

## Что было сделано

SwiftUI:
- ChatBubbleView

## Что необходимо протестировать

SwiftUI:
-Chat/TextMessage

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-08-31 07:17 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1387
Version: 1661929795
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1387

2022-08-31 12:01 UTC, Evgeniy-93 approved these changes

2022-09-02 09:40 UTC, ton252 approved these changes

2022-09-02 09:40 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusViewScheme.swift
> +    public init(theme: AppTheme = .default) {
convenience init

2022-09-02 09:40 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleViewScheme.swift
>      public init(theme: AppTheme) {
convenience init

2022-09-06 12:50 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1438
Version: 1662468159
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1438

2022-09-06 12:59 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1439
Version: 1662468721
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1439

2022-09-06 16:25 UTC, Almazovivan approved these changes

2022-09-06 18:47 UTC, Andyatkov requested changes

2022-09-06 18:47 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusView.swift
> +    /// The time of ChatBubbleStatusView
Мне кажется, если уже писать комменты, то более информативно, а то от таких комментов нет смысла
Здесь как пример написать, что время располагается в правом нижнем углу, рекомендуемый формат HH:mm

2022-09-06 18:47 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusView.swift
> +    /// The status of ChatBubbleStatusView
Здесь написать для чего нужны статусы и перечислить какие есть

2022-09-06 18:47 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusView.swift
> +    /// The direction of ChatBubbleStatusView
Здесь описать, что есть направление сообщения, и оно может либо прижато слева, либо прижато справа

2022-09-06 18:47 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusView.swift
> +    /// The style of ChatBubbleStatusView
Здесь описать какие бывают стили сообщения и для чего нужно

2022-09-06 18:47 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusViewScheme.swift
> +    /// The text font of ChatBubbleStatusViewScheme
Зачем писать "of ChatBubbleStatusViewScheme" ?

2022-09-06 18:47 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusViewScheme.swift
> +    /// The text color of ChatBubbleStatusViewScheme
Зачем писать "of ChatBubbleStatusViewScheme" ?

2022-09-06 18:47 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusViewScheme.swift
>      public var imageColor = ChatBubbleStatusViewParameters<AColor>()
Зачем писать "of ChatBubbleStatusViewScheme" ?
Здесь можно описать для какой картинки font color

2022-09-07 10:37 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusView.swift
> +    /// The status of ChatBubbleStatusView
+

2022-09-07 10:38 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleStatusView.swift
> +    /// The direction of ChatBubbleStatusView
+

2022-09-09 12:32 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1488
Version: 1662726307
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1488

2022-09-09 13:47 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1496
Version: 1662730814
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/3
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1496

2022-09-09 15:54 UTC, KirBorisov96 commented
Platform: iOS
Internal Version: 15
Branch Name: feature/392-swiftui-views-doc/3

2022-09-12 06:56 UTC, Andyatkov approved these changes

2022-09-12 08:11 UTC, merged