[392] - SwiftUI Refactoring PinCodeNumberView
admiral-team/admiralui-ios pull request #474
Opened 2022-08-31 13:47 UTC by KirBorisov96

# Задача

SwiftUI PinCodeNumberView

## Что было сделано

SwiftUI PinCodeNumberView

## Что необходимо протестировать

SwiftUI PinCodeNumberView

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-08-31 14:11 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1400
Version: 1661954707
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/18
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1400

2022-08-31 14:20 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1401
Version: 1661955207
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/18
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1401

2022-09-01 11:46 UTC, Evgeniy-93 submitted a review, later dismissed

2022-09-02 09:02 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Views/PinCodeKeyboard/Views/PinCodeNumberView/PinCodeNumberViewScheme.swift
> +    public init(
опять же вопрос с параметрами

2022-09-02 09:03 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Views/PinCodeKeyboard/Views/PinCodeTextView/PinCodeTextViewScheme.swift
> +        textFont = SwiftUI.Font.system(size: 36.0)
фигово, так делать нельзя

2022-09-02 09:08 UTC, ton252 approved these changes

2022-09-02 09:08 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Views/PinCodeKeyboard/Views/PinCodeTextView/PinCodeTextViewScheme.swift
> +        textFont = SwiftUI.Font.system(size: 36.0)
И ты даже глазом не моргнул, что у тебя в тестах верстка поехала

2022-09-02 09:08 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Views/PinCodeKeyboard/Views/PinCodeTextView/PinCodeTextViewScheme.swift
> +        textFont = SwiftUI.Font.system(size: 36.0)
Я вообще не понимаю, что там в тестах с темами

2022-09-06 13:24 UTC, Almazovivan approved these changes

2022-09-06 17:58 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1462
Version: 1662486709
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/18
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1462

2022-09-06 18:07 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1463
Version: 1662487216
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/18
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1463

2022-09-06 18:16 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1464
Version: 1662487743
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/18
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1464

2022-09-09 14:27 UTC, Evgeniy-93 submitted a review, later dismissed

2022-09-12 07:15 UTC, Andyatkov requested changes

2022-09-12 07:15 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/PinCodeKeyboard/Views/PinCodeNumberView/PinCodeNumberViewScheme.swift
> +    /// The background color
вроде не  background color

2022-09-12 07:15 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/PinCodeKeyboard/Views/PinCodeNumberView/PinCodeNumberViewScheme.swift
> +    /// The background color
и это тоже не background color

2022-09-12 07:15 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/PinCodeKeyboard/Views/PinCodeNumberView/PinCodeNumberViewScheme.swift
> +    /// The background color
и это тоже не background color

2022-09-12 07:15 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/PinCodeKeyboard/Views/PinCodeTextView/PinCodeTextViewScheme.swift
> +        textFont = SwiftUI.Font.system(size: 36.0)
Эмм, так не должно быть, фонт точно должен быть из темы, надо Насте написать, чтобы она поменяла в дизе и чтобы выбрала из того чего есть

2022-09-12 09:44 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1532
Version: 1662975438
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/18
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1532

2022-09-28 15:20 UTC, closed without merging