[392] - SwiftUI ToastView refactoring
admiral-team/admiralui-ios pull request #476
Opened 2022-08-31 14:41 UTC by KirBorisov96

# Задача

SwiftUI ToastView

## Что было сделано

SwiftUI ToastView

## Что необходимо протестировать

----

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-08-31 14:52 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1404
Version: 1661957104
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/20
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1404

2022-09-01 07:59 UTC, Evgeniy-93 approved these changes

2022-09-02 09:10 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Views/Toast/CountDownView/ClockView/ClockView.swift
> +struct Clock: View {
Опять приватная структура, вопрос, как извне без AppThemeSchemeProvider мы будем обновлять UI

2022-09-02 09:11 UTC, ton252 approved these changes

2022-09-02 09:11 UTC, ton252 commented on Source/AdmiralSwiftUI/Classes/Components/Views/Toast/CountDownView/ProgressBar/ProgressBar.swift
> +    @ObservedObject var schemeProvider = AppThemeSchemeProvider<ProgressBarScheme>()
аналогично

2022-09-05 16:05 UTC, Almazovivan submitted a review, later dismissed

2022-09-09 14:53 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1503
Version: 1662734801
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/20
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1503

2022-09-12 07:17 UTC, Andyatkov requested changes

2022-09-12 07:17 UTC, Andyatkov commented on Source/AdmiralSwiftUI/Classes/Components/Views/Toast/CountDownView/ProgressBar/ProgressBar.swift
> +    @ObservedObject var schemeProvider = AppThemeSchemeProvider<ProgressBarScheme>()
А почему здесь не передается schemeProvider?

2022-09-12 14:27 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1548
Version: 1662992389
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/20
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1548

2022-09-14 10:58 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1568
Version: 1663152664
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/20
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1568

2022-09-14 11:16 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1570
Version: 1663153756
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/20
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1570

2022-09-14 11:24 UTC, Evgeniy-93 approved these changes

2022-09-14 12:53 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Views/Toast/CountDownView/CoundDownView.swift
> +    @State var counter: Int = 0
не, мы меняем вьюху внутри, снаружи нету необходимости

2022-09-15 06:19 UTC, Andyatkov approved these changes

2022-09-15 07:43 UTC, Andyatkov approved these changes

2022-09-15 08:07 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1572
Version: 1663228831
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/392-swiftui-views-doc/20
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1572

2022-09-15 08:09 UTC, merged