[348] - AdmiralCore
admiral-team/admiralui-ios pull request #487
Opened 2022-09-01 14:26 UTC by KirBorisov96

# Задача

добавить AdmiralCore

## Что было сделано

добавлен AdmiralCore и вынесен ParameterBox из AdmiralTheme

## Что необходимо протестировать

--- Запустить проект 

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-09-04 14:33 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1412
Version: 1662301623
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/348-Themes-Refactring/AdmiralCore
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1412

2022-09-04 14:57 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1413
Version: 1662303007
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/348-Themes-Refactring/AdmiralCore
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1413

2022-09-05 08:48 UTC, Andyatkov requested changes

2022-09-05 08:48 UTC, Andyatkov commented on AdmiralCore.podspec
> +  spec.author             = { "" => "" }
Почему нет автора?

2022-09-05 08:48 UTC, Andyatkov commented on Source/AdmiralUIKit/Classes/Components/Common/ControlParameter.swift
> +import AdmiralCore
Почему поменялись скрины??

2022-09-05 11:16 UTC, Evgeniy-93 approved these changes

2022-09-07 07:04 UTC, KirBorisov96 commented on Source/AdmiralUIKit/Classes/Components/Common/ControlParameter.swift
> +import AdmiralCore
т.к вернул я xcode 12.5.1 и 14.5, разные версии влияют на снэпшот тесты

2022-09-07 07:04 UTC, KirBorisov96 commented on AdmiralCore.podspec
> +  spec.author             = { "" => "" }
хороший вопрос, их и в других подспеках нету

2022-09-07 07:38 UTC, Andyatkov commented on AdmiralCore.podspec
> +  spec.author             = { "" => "" }
Раньше здесь точно был Антон, и мы убрали после проверки, надо спросить у Антона, можем ли мы добавить его личную почту

2022-09-09 13:56 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1497
Version: 1662731377
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/348-Themes-Refactring/AdmiralCore
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1497

2022-09-09 14:06 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1498
Version: 1662731941
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/348-Themes-Refactring/AdmiralCore
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1498

2022-09-09 14:15 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1499
Version: 1662732493
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/348-Themes-Refactring/AdmiralCore
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1499

2022-09-12 07:24 UTC, Andyatkov requested changes
снепшоты

2022-09-12 10:02 UTC, Evgeniy-93 approved these changes

2022-09-12 15:05 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1551
Version: 1662994696
Internal Version: 15
Short Version: 0.0.0
Branch Name: feature/348-Themes-Refactring/AdmiralCore
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1551

2022-09-12 21:12 UTC, ton252 approved these changes

2022-09-13 06:59 UTC, Andyatkov approved these changes

2022-09-13 07:37 UTC, merged