[572] - Add UI test for Alerts
admiral-team/admiralui-ios pull request #573
Opened 2022-10-11 12:46 UTC by Evgeniy-93

# Задача Closes #572

## Что было сделано
Добавлены UI тесты для экранов Alerts

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-10-11 12:57 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1626
Version: 1665492629
Internal Version: 17
Short Version: 0.0.0
Branch Name: feature/572-Add-Alerts-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1626

2022-10-12 14:37 UTC, KirBorisov96 commented on ExampleiOS/Tests/AdmiralUIKitTests/AddUIKitAlertsTest.swift
> +    func testAlert() throws {
поскольку тут тесты на разные компоненты то нужно разбить тесты на файлы

2022-10-12 14:38 UTC, KirBorisov96 requested changes
Необходимы доработки

2022-10-13 14:08 UTC, Evgeniy-93 commented on ExampleiOS/Tests/AdmiralUIKitTests/AddUIKitAlertsTest.swift
> +    func testAlert() throws {
разложить файл на 4 файл по тестам

2022-12-12 14:30 UTC, closed without merging