[576] - Add UI Test for Bottom-sheet
admiral-team/admiralui-ios pull request #577
Opened 2022-10-11 13:29 UTC by Evgeniy-93

# Задача

## Что было сделано
Add UI Test for Bottom-sheet

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-10-11 13:41 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1628
Version: 1665495190
Internal Version: 17
Short Version: 0.0.0
Branch Name: feature/576-Add-BottomSheet-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1628

2022-10-12 14:30 UTC, KirBorisov96 commented on ExampleiOS/Tests/AdmiralUIKitTests/AddUIKitBottomSheetTest.swift
> +        app/*@START_MENU_TOKEN@*/.staticTexts["56 000.00 ₽"]/*[[".cells.staticTexts[\"56 000.00 ₽\"]",".staticTexts[\"56 000.00 ₽\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
ууууу еее, здесь бардак

2022-10-12 14:30 UTC, KirBorisov96 requested changes
надо убрать лишние символы их кода

2022-10-13 14:09 UTC, Evgeniy-93 commented on ExampleiOS/Tests/AdmiralUIKitTests/AddUIKitBottomSheetTest.swift
> +        app/*@START_MENU_TOKEN@*/.staticTexts["56 000.00 ₽"]/*[[".cells.staticTexts[\"56 000.00 ₽\"]",".staticTexts[\"56 000.00 ₽\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
поменять вручную клики на суммы

2022-12-01 12:56 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1739
Version: 1669898951
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/576-Add-BottomSheet-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1739

2022-12-12 17:10 UTC, KirBorisov96 approved these changes

2022-12-14 09:14 UTC, Almazovivan approved these changes

2022-12-15 10:39 UTC, Almazovivan approved these changes

2022-12-15 11:23 UTC, merged