[584] - Add UI test for Info
admiral-team/admiralui-ios pull request #585
Opened 2022-10-12 13:43 UTC by Evgeniy-93

# Задача

## Что было сделано
Add UI test for Info

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-10-12 13:54 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1634
Version: 1665582418
Internal Version: 17
Short Version: 0.0.0
Branch Name: feature/584-Add-Info-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1634

2022-10-12 14:24 UTC, KirBorisov96 approved these changes

2022-10-12 14:27 UTC, KirBorisov96 commented on ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitInfoTest.swift
> +
есть повторяющиеся блоки кода, напиши обсудим как быть

2022-10-12 14:27 UTC, KirBorisov96 requested changes
Необходима доработка

2022-10-13 14:22 UTC, Evgeniy-93 commented on ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitInfoTest.swift
> +
поменять темы как в currency

2022-10-21 11:29 UTC, Evgeniy-93 commented on ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitInfoTest.swift
> +
не получится поменять т/к в самом инфо нет кнопки смены темы

2022-12-01 12:29 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1737
Version: 1669897331
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/584-Add-Info-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1737

2022-12-12 17:12 UTC, KirBorisov96 requested changes
Нужна доработка

2022-12-15 10:44 UTC, KirBorisov96 approved these changes

2022-12-15 10:58 UTC, Almazovivan approved these changes

2022-12-15 12:19 UTC, merged