[586] - Add UI test for Contacts
admiral-team/admiralui-ios pull request #587
Opened 2022-10-12 14:20 UTC by Evgeniy-93

# Задача Closes #586

## Что было сделано
Add UI test for Contacts

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-10-12 14:23 UTC, KirBorisov96 submitted a review, later dismissed

2022-10-12 14:32 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1635
Version: 1665584661
Internal Version: 17
Short Version: 0.0.0
Branch Name: feature/586-Add-Contacts-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1635

2022-10-13 14:23 UTC, Evgeniy-93 commented
поправить как в currency

2022-12-12 10:38 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1742
Version: 1670841096
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/586-Add-Contacts-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1742

2022-12-12 17:13 UTC, KirBorisov96 requested changes
Нужна доработка, есть повторяющиеся блоки кода

2022-12-14 09:40 UTC, KirBorisov96 submitted a review, later dismissed

2022-12-15 12:43 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1755
Version: 1671107779
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/586-Add-Contacts-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1755

2022-12-15 16:28 UTC, closed without merging