[511] - Input number swiftUI
admiral-team/admiralui-ios pull request #593
Opened 2022-10-17 22:00 UTC by Andyatkov

# Задача

## Что было сделано
 Input number swiftUI
## Что необходимо протестировать
 Input number swiftUI

## Скриншоты(optional)

![Simulator Screen Shot - iPhone 13 - 2022-10-18 at 00 59 39](https://user-images.githubusercontent.com/8963238/196291827-a1de2a20-205d-4f87-9c22-f724ccf0e56b.png)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-10-17 22:11 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1642
Version: 1666044235
Internal Version: 17
Short Version: 0.0.0
Branch Name: feature/511-input-number
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1642

2022-10-18 07:38 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/NumberInputTextField/NumberInputButtonScheme.swift
> +
дока

2022-10-18 07:38 UTC, KirBorisov96 commented on Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/NumberInputTextField/NumberInputButtonScheme.swift
> +import SwiftUI
swiftui не нужен

2022-10-18 07:41 UTC, KirBorisov96 requested changes
думаю еще стоит написать парочку снэпшот тестов

2022-10-18 08:18 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1643
Version: 1666080656
Internal Version: 17
Short Version: 0.0.0
Branch Name: feature/511-input-number
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1643

2022-10-18 08:40 UTC, KirBorisov96 submitted a review, later dismissed

2022-10-19 15:18 UTC, Evgeniy-93 approved these changes

2022-10-21 11:14 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1653
Version: 1666350413
Internal Version: 17
Short Version: 0.0.0
Branch Name: feature/511-input-number
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1653

2022-10-21 11:19 UTC, Evgeniy-93 approved these changes

2022-10-21 11:33 UTC, KirBorisov96 approved these changes

2022-10-21 15:45 UTC, merged