[646] - Add UI test for Switcher and add id for buttons
admiral-team/admiralui-ios pull request #648
Opened 2022-11-15 09:08 UTC by Evgeniy-93

# Задача Closes #646

## Что было сделано
Add UI test for Switcher and add id for buttons

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-11-29 14:39 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1726
Version: 1669732304
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/646-Add-Switcher-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1726

2022-12-12 17:18 UTC, KirBorisov96 commented on ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Switcher/SwitcherViewController.swift
>          segmentControl.selectedSegmentIndex = 0
cmd A + control I

2022-12-12 17:19 UTC, KirBorisov96 requested changes
Выравнивание кода сделай и ок

2022-12-12 18:05 UTC, Evgeniy-93 commented on ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Switcher/SwitcherViewController.swift
>          segmentControl.selectedSegmentIndex = 0
готово

2022-12-14 09:16 UTC, Almazovivan approved these changes

2022-12-14 09:37 UTC, KirBorisov96 approved these changes

2022-12-16 12:23 UTC, merged