[557] - Add Radiobutton UI test
admiral-team/admiralui-ios pull request #650
Opened 2022-11-17 15:00 UTC by Evgeniy-93

# Задача

## Что было сделано
Добавлен UI тест для экрана Radiobutton

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-11-17 15:12 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1710
Version: 1668697464
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/557-Add-Radiobutton-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1710

2022-11-22 10:08 UTC, KirBorisov96 approved these changes

2022-11-28 16:04 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1719
Version: 1669650997
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/557-Add-Radiobutton-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1719

2022-11-29 10:55 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1725
Version: 1669718861
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/557-Add-Radiobutton-UI-Test
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1725

2022-11-29 14:59 UTC, Almazovivan approved these changes

2022-12-12 17:20 UTC, KirBorisov96 commented on ExampleiOS/Source/Classes/UserStrories/Main/UIKit/RadioButton/RadioButtonViewController.swift
>          segmentControl.selectedSegmentIndex = 0
Выравнивание кода Command A + Control I

2022-12-12 17:20 UTC, KirBorisov96 requested changes
нужно выравнивание

2022-12-12 18:03 UTC, Evgeniy-93 commented on ExampleiOS/Source/Classes/UserStrories/Main/UIKit/RadioButton/RadioButtonViewController.swift
>          segmentControl.selectedSegmentIndex = 0
готово

2022-12-16 12:23 UTC, merged