[331] - Changed UI test with accessibility
admiral-team/admiralui-ios pull request #658
Opened 2022-11-27 13:45 UTC by Evgeniy-93

# Задача

Themes - Icons - Buttons
## Что было сделано

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-11-30 11:39 UTC, Almazovivan submitted a review, later dismissed

2022-12-14 09:26 UTC, KirBorisov96 commented on ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIIconsTest.swift
>          app.tables/*@START_MENU_TOKEN@*/.staticTexts["Icons"]/*[[".cells.staticTexts[\"Icons\"]",".staticTexts[\"Icons\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
что за фигня тут ?

2022-12-14 09:26 UTC, KirBorisov96 commented on ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitButtonsTest.swift
>          app.tables/*@START_MENU_TOKEN@*/.staticTexts["Primary buttons"]/*[[".cells.staticTexts[\"Primary buttons\"]",".staticTexts[\"Primary buttons\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap(
здесь тоже, когда копируешь обращай внимание

2022-12-14 09:29 UTC, KirBorisov96 requested changes
выравнивание кода + убрать лишние символы

2022-12-14 09:47 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1746
Version: 1671010768
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/331-Add-Themes-Icons-Buttons-UI-Tests
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1746

2022-12-15 12:19 UTC, merged