[670] - Add UI test for Page Controls Circle
admiral-team/admiralui-ios pull request #671
Opened 2022-12-12 09:59 UTC by Evgeniy-93

# Задача

## Что было сделано

Add UI test for Page Controls Circle

## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2022-12-12 11:00 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1744
Version: 1670842400
Internal Version: 18
Short Version: 11.1.1
Branch Name: feature/670-Add-UI-Test-PageControls-Circle
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1744

2022-12-12 14:44 UTC, Almazovivan commented on ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIPageControlsCircleTest.swift
> +
Тут сегменты нужно тапать через ацесабилити

2022-12-12 14:44 UTC, Almazovivan commented on ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIPageControlsCircleTest.swift
> +        app.buttons["arrowRight"].tap()
Тут тоже ацесабилити

2022-12-12 17:28 UTC, KirBorisov96 requested changes
нужны доработки

2022-12-12 17:55 UTC, Evgeniy-93 commented on ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIPageControlsCircleTest.swift
> +        app.buttons["arrowRight"].tap()
добавьте тогда плиз ацесабилити для цифр и для стрелки

2022-12-15 11:25 UTC, Almazovivan approved these changes

2022-12-15 11:29 UTC, Almazovivan approved these changes

2022-12-15 12:19 UTC, merged