[TECH] - Fix swiftlint errors
admiral-team/admiralui-ios pull request #844
Opened 2023-05-25 08:40 UTC by Andyatkov

# Задача Closes #0

## Что было сделано
Добавлен swiftlint для AdmiralUI
Исправлены swiftlint ошибки(НУЖНО еще поправить ворнинги)
## Что необходимо протестировать

## Скриншоты(optional)

# Review

**Иван Алмазов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Кирилл Борисов**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

**Андрей Дятков**

- [ ] Все публичные свойства и методы задокументированы 
- [ ] Нейминг переменных и функций
- [ ] Проверка на дублированость кода
- [ ] Проверка на magic константы
- [ ] Проверка на [weak self]
- [ ] Расставлены правильно все MARK и отступы
- [ ] Добавлены UI тесты на новые UI элементы
- [ ] Разбитие на подфункции/на логические блоки
- [ ] Перенос после "("
- [ ] Проверка на грамматику
- [ ] Модификаторы доступа 
- [ ] Проверка на неиспользуемые элементы в коде
- [ ] Проверка на удаление тестированного кода

# Review QA

**Тестирование**

- [ ] Проверка UI элемента
- [ ] Проверка скринов после UI тестирования
- [ ] Проверка в темной/светлой теме
- [ ] Проверка локализации
- [ ] Соотвествие дизайну

2023-05-25 08:51 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1926
Version: 1685004289
Internal Version: 24
Short Version: 11.4.0
Branch Name: bugfix/tech-swift-lint
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1926

2023-05-25 11:38 UTC, Evgeniy-93 approved these changes

2023-05-25 13:14 UTC, Evgeniy-93 submitted a review, later dismissed

2023-05-25 14:05 UTC, ton252 requested changes

2023-05-25 14:05 UTC, ton252 commented on ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
> +    public static let photo = ImageAsset(name: "Chat/Photo")
Почему у нас файлы называют кто как хочет? Почему названия иконок с большой буквы, хотя по стандарту везде с маленькой. И вообще не понял, как в этом пулл-реквесте может быть такое изменение, если ты выполнял работу по линтеру.

2023-05-25 14:24 UTC, KirBorisov96 approved these changes

2023-05-25 14:28 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1931
Version: 1685024664
Internal Version: 24
Short Version: 11.4.0
Branch Name: bugfix/tech-swift-lint
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1931

2023-05-25 14:44 UTC, KirBorisov96 approved these changes

2023-05-31 09:13 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1954
Version: 1685524192
Internal Version: 25
Short Version: 0.0.0
Branch Name: bugfix/tech-swift-lint
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1954

2023-05-31 10:11 UTC, KirBorisov96 submitted a review, later dismissed

2023-05-31 10:38 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 1955
Version: 1685529273
Internal Version: 25
Short Version: 0.0.0
Branch Name: bugfix/tech-swift-lint
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1955

2023-06-06 10:40 UTC, closed without merging